<template>
    <div class="books-items">
      <div class="book-image" >
        <figure @click="toBook">     
          <img :src="book.cover_picture" alt="book" height="200" width="150"/>
        </figure>
      </div>

      <b-row>
        <b-col cols="9"><strong>{{book.name}}</strong></b-col>
        <b-col ><b-icon :icon="iconLike" @click="onLikeChange"></b-icon>   </b-col>
    </b-row>

      
      <div class="books-content" @click="toBook">
          <small>{{book.author}}</small>            
      </div>
      <small @click="toBook">{{book.category}}</small>
      <br>
        
    </div>
       
         
</template>

<script>
import {mapState} from 'vuex'
export default {
    props: ['book','edit'],
    data(){
      return{
        iconLike: 'heart',
        like: false
      }
    },
    computed: mapState(['booksLiked','user']),
    methods:{
        toBook(){
            this.$router.push({ name:'book-details', params: {id: this.book._id, book: this.book}})
        },
        onLikeChange(){

         
          this.book.like = !this.book.like
          this.$emit('update', this.book)
          if(this.book.like){
            this.$store.commit("setBooksLiked", this.book)
          } else{
            this.$store.commit("removeBooksLiked", this.book)
          }
        
          this.book.like ? this.iconLike ='heart-fill' : this.iconLike = 'heart'
        }
    },
    mounted(){

      this.book.like ? this.iconLike ='heart-fill' : this.iconLike = 'heart'
        
    },
    watch:{
      'book':function(){
        this.book.like ? this.iconLike ='heart-fill' : this.iconLike = 'heart'
      }
    }
}
</script>

<style>
.book-items{
    margin-top: 2%;
    background-color: transparent;
}

.book-image:hover{
  cursor:pointer;
}
/*! Generated by Bulma Customizer v0.2.0 | https://github.com/webmasterish/bulma-customizer */

.book-image {
  background-color: transparent;
  align-items: center;
  display: flex;
  flex-direction: row;
  flex-grow: 1;
  font-weight: 700;
  padding: 0.75rem 1rem;
  justify-content: center;
}

.books-items {
  display:flex;
  background-color: transparent;
  flex-direction: column;
  justify-content: center;
  max-width: 100%;
}

.books-content {
  display:flex;
  background-color: transparent;
  flex-direction: row;
  justify-content: space-between;
}

.books-items:hover{
  cursor:pointer;
}
.books-content:hover{
  cursor:pointer;
}


</style>