import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { CoursesProvider } from "@/context/SearchContext";
import Navbar from "@/components/Navbar";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang='en'>
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <CoursesProvider>
          <div className='min-h-screen flex flex-col bg-gray-50 text-gray-800'>
            <Navbar />
            <main className='flex-1'>{children}</main>
            <footer className='bg-white border-t text-sm text-center text-gray-500 py-4 mt-8'>
              © {new Date().getFullYear()} Plataforma de Cursos. Todos os
              direitos reservados.
            </footer>
          </div>
        </CoursesProvider>
      </body>
    </html>
  );
}
