export const FETCHING_BOOKS_SUCCESS = 'FETCHING_BOOKS_SUCCESS'
export const FETCHING_BOOKS_ERROR = 'FETCHING_BOOKS_ERROR'

export const SET_BOOK_SUCCESS = 'SET_BOOK_SUCCESS'
export const SET_BOOK_ERROR = 'SET_BOOK_ERROR'

export const LIKE_BOOK_SUCCESS = 'LIKE_BOOK_SUCCESS'
export const LIKE_BOOK_ERROR = 'LIKE_BOOK_ERROR'

export const UNLIKE_BOOK_SUCCESS = 'UNLIKE_BOOK_SUCCESS'
export const UNLIKE_BOOK_ERROR = 'UNLIKE_BOOK_ERROR'

export const SHOW_LOADER = 'SHOW_LOADER'
export const HIDE_LOADER = 'HIDE_LOADER'

export const SET_THEME_DARK = 'SET_THEME_DARK'
export const SET_THEME_LIGHT = 'SET_THEME_LIGHT'
